### ISSUE TITLE
Skylake support?

### ISSUE THREAD

**Issue by oscarbg** [maurossi/mesa#2]
Hi,
just thinking about getting Skylake PC.. will GPU be supported? seems needs new kernel 4.2 or 4.3 can you provide some build with latest kernel and Mesa posible for testing with new PCs?

**Comment by maurossi** [comment]
Kernel 4.3 is in my desires list too, because I want to see if nouveau
lockups are finally prevented.

I will play with kernel 4.3rc and you may see some reportage on the forum,
but it may take weeks.

In the meantime you could check if lollipop-x86 ISO works, because kernel
4.0.9 is built forcing the needed parameter and you could also get feedback
in Miker's Android-x86 forum about the status for Skylake.

Mauro

Il giovedì 8 ottobre 2015, Oscar Barenys notifications@github.com ha
scritto:

**Comment by maurossi** [comment]
Closing as now supported with new kernels
