### ISSUE TITLE
17.3.1 Oreo 32bit Intel 965gm

### ISSUE THREAD

**Issue by francisuk1989** [maurossi/mesa#3]
Hello, I think theres a problem with 17.3.1_oreo-x86, Im experiencing issues with video apps like youtube, it will only play audio and shows a blank video screen but audio plays fine, I have tryed loading a MP4 enoded to x264 from https://peach.blender.org/download (Open movie project) however mpv just crashes out.

So could this be a problem with 17.3.1 for Intel 965GM, Also with this 17.3.1 my screen resolution has changed what has inproved but no video playback.

**Comment by maurossi** [comment]
Please provide information and logs,

because if the problem does not appear in 17.3.0 (x86/oreo-x86 branch) and appears in 17.3.1, I have only merged upstream mesa/17.3 branch in oreo-x86 branch

So it is highly probable that:
1)  problem is already happening with 17.3.0  in the exact same conditions, i.e oreo 8.1.0r1 in both cases,then it is not even a problem with mesa,but other components in oreo-x86 build.
2) if not happening with mesa 17.3.0 and happening systematically with 17.3.1_oreo-x86, in the exact same conditions, i.e oreo 8.1.0r1 in both cases,  we would need to open a bug to mesa 17.3 branch

but please provide dmesg/logcat to assess.

Please also provide feedback on mesa-dev (latest 17.4.0devel) available in:
https://drive.google.com/drive/folders/0B_OFHiIqgpSFTFpkQWc1eXV3ME0

**Comment by maurossi** [comment]
Hi, closing because oreo-x86 moved to mesa 18.3.6
