### ISSUE TITLE
amdgpu_bo_import and amdgpu_bo_free calls are not balanced, which leaks amdgpu_bo if using mesa and gbm gralloc together.

### ISSUE THREAD

**Issue by lamianlbe** [maurossi/mesa#4]
amdgpu_bo.c in libdrm uses reference counting to track usage of each amdgpu_bo. amdgpu_bo_import increases reference count and amdgpu_bo_free decreases it.

in mesa, each time when amdgpu_bo_from_handle is called, it calls amdgpu_bo_import to get amdgpu_bo and build amdgpu_winsys_bo. Because amdgpu_winsys_bo is also reference counted, amdgpu_bo_free will be called only once for each amdgpu_winsys_bo.

so, for one amdgpu_bo, if amdgpu_bo_from_handle is called for more than once, amdgpu_bo_import and amdgpu_bo_free calls will be unbalanced.

Tested on Mesa 18.2.0 + GBM gralloc, Android 7.1.2-r36, AMD Radeon RX560

**Comment by maurossi** [comment]
Hi,

if you understood all of it, because I didn't, sorry,  import, refcounting, handles is one my many weak spots, 

please open a bug to mesa with bugzilla freedesktop with traces and logs or some other evidence of the leak and AMD mantainers of amdgpu winsys will evaluate how to fix it
and also it will be mainstreamed in mesa without intermediaries/men-in-the-middle

In case you have completed the build of nougat-x86 with gbm gralloc during your tests, please provide or publish the procedure or manifest in the android-x86 forum, because many people asked about it, because they were stuck with explicit sync fences API build errors, but I'm not able to test & publish myself soon, because I'm working on AMD DC for Southern islands to get Vulkan radv support.

Thanks

Mauro

**Comment by lamianlbe** [comment]
sorry, my bad, because I use your mesa branch and I'm not quite familiar with mesa architecture. I will open a bug on freedesktop bugzilla and close this one. My apologize for inconvenience.

about my android x86 build, I'm working on a android container project which tries to run multiple android instances on one bare metal server. since the framebuffers are encoded to h264 and transferred over network, custom gralloc and hwcomposer are implemented, which is quite different from android-x86 ones.

I think that's why I didn't get any sync fence API build errors on my nougat builds, but that also means my experience can do very little help to android x86 users.

Thanks.
